/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sabri
 */
public class booklist extends javax.swing.JFrame {

    /**
     * Creates new form booklist
     */
    public booklist() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        scfictxt = new javax.swing.JLabel();
        scfic = new javax.swing.JLabel();
        horrortxt = new javax.swing.JLabel();
        horror = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        travel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        kids = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        listOfBooks = new javax.swing.JLabel();
        thirdBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        scfictxt.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        scfictxt.setForeground(new java.awt.Color(255, 255, 255));
        scfictxt.setText("Science Fiction");
        jPanel1.add(scfictxt);
        scfictxt.setBounds(60, 210, 140, 50);

        scfic.setIcon(new javax.swing.ImageIcon("D:\\Study\\CSE\\Level-2, Term-2\\CSE-220 OOP Sessional-II\\Project\\Book Store\\image\\Science-Fiction1.jpg")); // NOI18N
        scfic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scficMouseClicked(evt);
            }
        });
        jPanel1.add(scfic);
        scfic.setBounds(40, 130, 170, 230);

        horrortxt.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        horrortxt.setForeground(new java.awt.Color(255, 255, 255));
        horrortxt.setText("Horror");
        jPanel1.add(horrortxt);
        horrortxt.setBounds(260, 300, 130, 48);

        horror.setIcon(new javax.swing.ImageIcon("D:\\Study\\CSE\\Level-2, Term-2\\CSE-220 OOP Sessional-II\\Project\\Book Store\\image\\horror3.jpg")); // NOI18N
        horror.setText("jLabel4");
        horror.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                horrorMouseClicked(evt);
            }
        });
        jPanel1.add(horror);
        horror.setBounds(240, 130, 170, 230);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel1.setText("Travel");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(470, 160, 110, 40);

        travel.setIcon(new javax.swing.ImageIcon("D:\\Study\\CSE\\Level-2, Term-2\\CSE-220 OOP Sessional-II\\Project\\Book Store\\image\\travel.png")); // NOI18N
        travel.setText("jLabel1");
        travel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                travelMouseClicked(evt);
            }
        });
        jPanel1.add(travel);
        travel.setBounds(440, 130, 170, 230);

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel2.setText("kids");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(690, 160, 50, 40);

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel3.setText("story");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(690, 190, 60, 40);

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel4.setText("Books");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(690, 220, 80, 40);

        kids.setIcon(new javax.swing.ImageIcon("D:\\Study\\CSE\\Level-2, Term-2\\CSE-220 OOP Sessional-II\\Project\\Book Store\\image\\kidsjpg.jpg")); // NOI18N
        kids.setText("jLabel2");
        kids.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kidsMouseClicked(evt);
            }
        });
        jPanel1.add(kids);
        kids.setBounds(640, 130, 170, 230);

        backButton.setBackground(new java.awt.Color(204, 204, 255));
        backButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backButton);
        backButton.setBounds(720, 400, 110, 40);

        listOfBooks.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        listOfBooks.setText("The following categories are available:");
        jPanel1.add(listOfBooks);
        listOfBooks.setBounds(40, 60, 690, 40);

        thirdBackground.setIcon(new javax.swing.ImageIcon("D:\\Study\\CSE\\Level-2, Term-2\\CSE-220 OOP Sessional-II\\Project\\Book Store\\image\\booklistImage_2.jpg")); // NOI18N
        thirdBackground.setText("jLabel1");
        jPanel1.add(thirdBackground);
        thirdBackground.setBounds(0, 0, 860, 460);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 861, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        SigninForm obj = new SigninForm();
        obj.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_backButtonActionPerformed

    private void scficMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scficMouseClicked
        // TODO add your handling code here:
        ScienceFictionBooks scfic = new ScienceFictionBooks();
        scfic.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_scficMouseClicked

    private void horrorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_horrorMouseClicked
        // TODO add your handling code here:
        HorrorBooks horror = new HorrorBooks();
        horror.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_horrorMouseClicked

    private void travelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_travelMouseClicked
        // TODO add your handling code here:
        travelBooks travel = new travelBooks();
        travel.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_travelMouseClicked

    private void kidsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kidsMouseClicked
        // TODO add your handling code here:
        kidBooks kids = new kidBooks();
        kids.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_kidsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(booklist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(booklist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(booklist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(booklist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new booklist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel horror;
    private javax.swing.JLabel horrortxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel kids;
    private javax.swing.JLabel listOfBooks;
    private javax.swing.JLabel scfic;
    private javax.swing.JLabel scfictxt;
    private javax.swing.JLabel thirdBackground;
    private javax.swing.JLabel travel;
    // End of variables declaration//GEN-END:variables
}
