/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sabri
 */
public class kidBooks extends javax.swing.JFrame {

    /**
     * Creates new form kidBooks
     */
    public kidBooks() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        kidsTxt = new javax.swing.JLabel();
        kidsBokkList = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        selectButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        kidsBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        kidsTxt.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        kidsTxt.setText("Choose Books for kids you'de like to buy:");
        jPanel1.add(kidsTxt);
        kidsTxt.setBounds(50, 20, 740, 50);

        jList1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "1. The Secrets of Droon by Tony Abbott......................................210 Tk", "2. Encyclopedia Brown by Donald J. Sobol...................................320 Tk", "3. Superspecial by C. Alexander London......................................240 Tk", "4. Captain Underpants by Dav Pilkey...........................................190 Tk", "5. The Borrowers by Mary Norton...............................................320 Tk", "6. The Baby-Sitters Club by Ann M. Martin...................................200 Tk", "7. The Heroes of Olympus by Rick Riordan...................................260 Tk", "8. Nancy Drew Mystery Stories by Carolyn Keene..........................210 Tk", "9. Doctor Dolittle by Hugh Lofting.................................................260 Tk", "10. The Kane Chronicles by Rick Riordan......................................230 Tk", "11. Diary of a Wimpy Kid by Jeff Kinney........................................190 Tk", "12. Redwall by Brian Jacques......................................................200 Tk", "13. School Friends by Ann Bryant................................................400 Tk", "14. The Black Stallion by Walter Farley and Steven Farley..............350 Tk", "15. The Hardy Boys by Franklin W. Dixon......................................200 Tk", "16. Alice by Lewis Carroll............................................................310 Tk", "17. The Famous Five by Bnid Blyton.............................................230 Tk", "18. Jennings by Anthony Buckeridge.............................................180 Tk", "19. Lola Levine\tby Monica Brown..................................................260 Tk", "20. Three Thieves by Scott Chantler.............................................150 Tk" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        kidsBokkList.setViewportView(jList1);

        jPanel1.add(kidsBokkList);
        kidsBokkList.setBounds(20, 80, 820, 310);

        selectButton.setBackground(new java.awt.Color(204, 204, 255));
        selectButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        selectButton.setText("Select");
        selectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectButtonActionPerformed(evt);
            }
        });
        jPanel1.add(selectButton);
        selectButton.setBounds(590, 400, 110, 40);

        backButton.setBackground(new java.awt.Color(204, 204, 255));
        backButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backButton);
        backButton.setBounds(720, 400, 110, 40);

        kidsBackground.setIcon(new javax.swing.ImageIcon("D:\\Study\\CSE\\Level-2, Term-2\\CSE-220 OOP Sessional-II\\Project\\Book Store\\image\\kidsBackground.jpg")); // NOI18N
        jPanel1.add(kidsBackground);
        kidsBackground.setBounds(0, 0, 860, 460);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        booklist obj = new booklist();
        obj.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    private void selectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectButtonActionPerformed
        // TODO add your handling code here:
        buyBooks buy = new buyBooks();
        buy.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_selectButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kidBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kidBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kidBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kidBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kidBooks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel kidsBackground;
    private javax.swing.JScrollPane kidsBokkList;
    private javax.swing.JLabel kidsTxt;
    private javax.swing.JButton selectButton;
    // End of variables declaration//GEN-END:variables
}
