/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sabri
 */
public class paymentForm extends javax.swing.JFrame {

    /**
     * Creates new form paymentForm
     */
    public paymentForm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        phnTxt = new javax.swing.JLabel();
        phnfield = new javax.swing.JTextField();
        addressTxt = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Addressfield = new javax.swing.JTextArea();
        peymentTxT = new javax.swing.JLabel();
        CheckBoxBikash = new javax.swing.JCheckBox();
        CheckBoxDelivary = new javax.swing.JCheckBox();
        doneButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        paymentBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        phnTxt.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        phnTxt.setForeground(new java.awt.Color(255, 255, 255));
        phnTxt.setText("Enter your Phone Number:");
        jPanel1.add(phnTxt);
        phnTxt.setBounds(20, 140, 320, 40);

        phnfield.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        jPanel1.add(phnfield);
        phnfield.setBounds(330, 150, 360, 40);

        addressTxt.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        addressTxt.setForeground(new java.awt.Color(255, 255, 255));
        addressTxt.setText("Enter your Address: ");
        jPanel1.add(addressTxt);
        addressTxt.setBounds(20, 210, 230, 40);

        Addressfield.setColumns(20);
        Addressfield.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        Addressfield.setRows(5);
        jScrollPane1.setViewportView(Addressfield);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(250, 220, 560, 110);

        peymentTxT.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        peymentTxT.setForeground(new java.awt.Color(255, 255, 255));
        peymentTxT.setText("Choose your peyment method:");
        jPanel1.add(peymentTxT);
        peymentTxT.setBounds(20, 60, 360, 30);

        CheckBoxBikash.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        CheckBoxBikash.setForeground(new java.awt.Color(255, 255, 255));
        CheckBoxBikash.setText("Bikash");
        CheckBoxBikash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxBikashActionPerformed(evt);
            }
        });
        jPanel1.add(CheckBoxBikash);
        CheckBoxBikash.setBounds(370, 50, 110, 41);

        CheckBoxDelivary.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        CheckBoxDelivary.setForeground(new java.awt.Color(255, 255, 255));
        CheckBoxDelivary.setText("Cash on Delivary");
        CheckBoxDelivary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxDelivaryActionPerformed(evt);
            }
        });
        jPanel1.add(CheckBoxDelivary);
        CheckBoxDelivary.setBounds(500, 50, 220, 40);

        doneButton.setBackground(new java.awt.Color(204, 204, 255));
        doneButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        doneButton.setText("Done");
        doneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButtonActionPerformed(evt);
            }
        });
        jPanel1.add(doneButton);
        doneButton.setBounds(360, 390, 170, 50);

        backButton.setBackground(new java.awt.Color(204, 204, 255));
        backButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backButton);
        backButton.setBounds(710, 390, 110, 40);

        paymentBackground.setIcon(new javax.swing.ImageIcon("D:\\Study\\CSE\\Level-2, Term-2\\CSE-220 OOP Sessional-II\\Project\\Book Store\\image\\paymentBack.jpg")); // NOI18N
        jPanel1.add(paymentBackground);
        paymentBackground.setBounds(0, 0, 860, 460);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 858, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButtonActionPerformed
        // TODO add your handling code here:
        thanks tnx = new thanks();
        tnx.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_doneButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        buyBooks buy = new buyBooks();
        buy.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    private void CheckBoxBikashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxBikashActionPerformed
        // TODO add your handling code here:
        if(CheckBoxBikash.isSelected())
            CheckBoxDelivary.setSelected(false);
    }//GEN-LAST:event_CheckBoxBikashActionPerformed

    private void CheckBoxDelivaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxDelivaryActionPerformed
        // TODO add your handling code here:
        if(CheckBoxDelivary.isSelected())
            CheckBoxBikash.setSelected(false);
    }//GEN-LAST:event_CheckBoxDelivaryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(paymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(paymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(paymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(paymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new paymentForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Addressfield;
    private javax.swing.JCheckBox CheckBoxBikash;
    private javax.swing.JCheckBox CheckBoxDelivary;
    private javax.swing.JLabel addressTxt;
    private javax.swing.JButton backButton;
    private javax.swing.JButton doneButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel paymentBackground;
    private javax.swing.JLabel peymentTxT;
    private javax.swing.JLabel phnTxt;
    private javax.swing.JTextField phnfield;
    // End of variables declaration//GEN-END:variables
}
