/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sabri
 */
public class ScienceFictionBooks extends javax.swing.JFrame {

    /**
     * Creates new form ScienceFictionBooks
     */
    public ScienceFictionBooks() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        scficTxt = new javax.swing.JLabel();
        scficBooklist = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        confirmButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        scficBackgroun = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        scficTxt.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        scficTxt.setForeground(new java.awt.Color(255, 255, 255));
        scficTxt.setText("Choose Science Fiction Books you'de like to buy:");
        jPanel1.add(scficTxt);
        scficTxt.setBounds(90, 40, 670, 50);

        jList1.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        jList1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "1. Absolution Gap by Alastair Reynolds.................................230 Tk", "2. Air by Geoff Ryman.........................................................220 Tk", "3. Between Planets by Robert A. Heinlein..............................190 Tk", "4. City by Clifford D. Simak...................................................300 Tk", "5. Coalescent by Stephen Baxter...........................................280 Tk", "6. Days of Grass by Tanith Lee\t..............................................320 Tk", "7. The Domes of Pico by Hugh Walters...................................260 Tk", "8. Eon by Greg Bear..............................................................190 Tk", "9. Fossil by Hal Clement........................................................200 Tk", "10. The Gray Prince by Jack Vance.........................................240 Tk", "11. The House of the Scorpion by Nancy Farmer......................170 Tk", "12. Journey to Jupiter by Hugh Walters....................................290 Tk", "13. Killobyte by Piers Anthony\t...............................................240 Tk", "14. Lords of the Psychon by Daniel F. Galouye\t..........................110 Tk", "15. Man Plus by Frederik Pohl\t................................................210 Tk", "16. The Memory of Earth by Orson Scott Card\t..........................140 Tk", "17. The Pixel Eye by Paul Levinson...........................................280 Tk", "18. Pushing Ice by Alastair Reynolds........................................170 Tk", "19. Roadmarks by Roger Zelazny.............................................180 Tk", "20. Seveneves by Neal Stephenson..........................................200 Tk" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scficBooklist.setViewportView(jList1);

        jPanel1.add(scficBooklist);
        scficBooklist.setBounds(20, 110, 820, 280);

        confirmButton.setBackground(new java.awt.Color(204, 204, 255));
        confirmButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        confirmButton.setText("Select");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });
        jPanel1.add(confirmButton);
        confirmButton.setBounds(600, 400, 110, 40);

        backButton.setBackground(new java.awt.Color(204, 204, 255));
        backButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backButton);
        backButton.setBounds(730, 400, 110, 40);

        scficBackgroun.setIcon(new javax.swing.ImageIcon("D:\\Study\\CSE\\Level-2, Term-2\\CSE-220 OOP Sessional-II\\Project\\Book Store\\image\\Science-Fiction-background.jpg")); // NOI18N
        jPanel1.add(scficBackgroun);
        scficBackgroun.setBounds(0, 0, 860, 460);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        booklist obj = new booklist();
        obj.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        // TODO add your handling code here:
        buyBooks buy = new buyBooks();
        buy.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_confirmButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScienceFictionBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScienceFictionBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScienceFictionBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScienceFictionBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScienceFictionBooks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton confirmButton;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel scficBackgroun;
    private javax.swing.JScrollPane scficBooklist;
    private javax.swing.JLabel scficTxt;
    // End of variables declaration//GEN-END:variables
}
