
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.apache.poi.EncryptedDocumentException;
import org.apache.poi.openxml4j.exceptions.InvalidFormatException;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.ss.usermodel.WorkbookFactory;

public class SigninForm extends javax.swing.JFrame {

    /**
     * Creates new form SigninForm
     */
    public SigninForm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        whole = new javax.swing.JPanel();
        signinTxt = new javax.swing.JLabel();
        useridTxt = new javax.swing.JLabel();
        useridFld = new javax.swing.JTextField();
        passTxt = new javax.swing.JLabel();
        passFld = new javax.swing.JPasswordField();
        signinBtn = new javax.swing.JButton();
        signupBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        bdgPic = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        whole.setLayout(null);

        signinTxt.setFont(new java.awt.Font("Tempus Sans ITC", 1, 48)); // NOI18N
        signinTxt.setForeground(new java.awt.Color(204, 255, 255));
        signinTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signinTxt.setText("Sign In");
        whole.add(signinTxt);
        signinTxt.setBounds(200, 20, 450, 70);

        useridTxt.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        useridTxt.setForeground(new java.awt.Color(204, 255, 255));
        useridTxt.setText("User ID");
        whole.add(useridTxt);
        useridTxt.setBounds(280, 110, 100, 33);

        useridFld.setBackground(new java.awt.Color(204, 255, 255));
        useridFld.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        whole.add(useridFld);
        useridFld.setBounds(280, 150, 300, 30);

        passTxt.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        passTxt.setForeground(new java.awt.Color(204, 255, 255));
        passTxt.setText("Password");
        whole.add(passTxt);
        passTxt.setBounds(280, 190, 130, 30);

        passFld.setBackground(new java.awt.Color(204, 255, 255));
        whole.add(passFld);
        passFld.setBounds(280, 230, 300, 30);

        signinBtn.setBackground(new java.awt.Color(204, 255, 255));
        signinBtn.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        signinBtn.setForeground(new java.awt.Color(0, 51, 51));
        signinBtn.setText("Sign In");
        signinBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinBtnActionPerformed(evt);
            }
        });
        whole.add(signinBtn);
        signinBtn.setBounds(370, 290, 120, 40);

        signupBtn.setBackground(new java.awt.Color(153, 153, 153));
        signupBtn.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        signupBtn.setForeground(new java.awt.Color(51, 0, 153));
        signupBtn.setText("Need An Account? Just Sign Up!");
        signupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupBtnActionPerformed(evt);
            }
        });
        whole.add(signupBtn);
        signupBtn.setBounds(180, 350, 500, 50);

        backBtn.setBackground(new java.awt.Color(204, 204, 255));
        backBtn.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        whole.add(backBtn);
        backBtn.setBounds(720, 400, 110, 40);

        bdgPic.setIcon(new javax.swing.ImageIcon("D:\\Study\\CSE\\Level-2, Term-2\\CSE-220 OOP Sessional-II\\Project\\Book Store\\image\\signinform.jpg")); // NOI18N
        whole.add(bdgPic);
        bdgPic.setBounds(0, 0, 860, 460);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(whole, javax.swing.GroupLayout.DEFAULT_SIZE, 859, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(whole, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        initialPage initPage = new initialPage();
        initPage.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backBtnActionPerformed

    private static Workbook wb;
    private static FileInputStream fis;
    private static Sheet sh;
    private static Row row;
    private static Cell cell;
    private static FileOutputStream fos;
    private boolean matchOrNot(){
        String ID = useridFld.getText();
        String pass = passFld.getText();
        try {
           fis  = new FileInputStream("Database//Signinform.xlsx");
           try {
               try {
                   wb = WorkbookFactory.create(fis);
               } catch (InvalidFormatException ex) {
                   Logger.getLogger(SigninForm.class.getName()).log(Level.SEVERE, null, ex);
               }
               sh = wb.getSheet("Sheet1");
               int noOfRows = sh.getLastRowNum()+1;
//               System.out.println(noOfRows);
               String [][]data = new String[noOfRows][4];
               int tempRowCount=0,tempColCount=0;
               for (Row row : sh) {
                   for (Cell cell : row) {
                       cell.setCellType(Cell.CELL_TYPE_STRING);
                       String temp = (String)cell.getStringCellValue();
                       if(temp==null){
                           JOptionPane.showMessageDialog(this, "Database Error", "Database Incomplete", JOptionPane.ERROR_MESSAGE);
                           new booklist().setVisible(true);
                       }
                       tempColCount++;
                   }
                   tempRowCount++;
               }
               for (int i = sh.getFirstRowNum(); i <= sh.getLastRowNum(); i++) {
                   Row r = sh.getRow(i);
                   for (int j = r.getFirstCellNum(); j < r.getLastCellNum(); j++) {
                       Cell c = r.getCell(j);
                       data[i][j] = c.getStringCellValue();
                       System.out.println(data[i][j]);
                   }
               }
               for (int i = 0; i < noOfRows; i++) {
//                        System.out.println(noOfRows);
//                        if(!ID.equals(data[i][3]))
//                            System.out.println(data[i][3]);
//                        if(!pass.equals(data[i][2]))
//                            System.out.println(data[i][2]);
                   if(ID.equals(data[i][3])&& pass.equals(data[i][2])){
//                       System.out.println("okay");
                       fis.close();
                       return true;
                   }
//                   System.out.println(i);
               }
               fis.close();
//                break;
//                    continue start;
            }catch (IOException ex) {
                System.out.println("From wb");
//                Logger.getLogger(loginForm.class.getName()).log(Level.SEVERE, null, ex);
            }
//                Logger.getLogger(loginForm.class.getName()).log(Level.SEVERE, null, ex);
             catch (EncryptedDocumentException ex) {
                System.out.println("From wb");
//                Logger.getLogger(loginForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (FileNotFoundException ex) {
            System.out.println("From fis");
//            Logger.getLogger(loginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
//        continue start;
        return false;
    }
    
    
    private void signinBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinBtnActionPerformed

        boolean result = matchOrNot();
        if (result==true){
            useridFld.setText("");
            passFld.setText("");
            new booklist().setVisible(true);
            this.setVisible(false);
        }
        else{
            JOptionPane.showMessageDialog(this, "The Data You Have Entered Are Wrong!\nTry Using The Correct Ones!", "Data Incorrect!", JOptionPane.ERROR_MESSAGE);
            useridFld.setText("");
            passFld.setText("");
            matchOrNot();
        }
        
        
        
        
        /*booklist ob = new booklist();
        ob.setVisible(true);
        this.setVisible(false);*/
        
        
        //JOptionPane.showMessageDialog(this, "Wrong User ID or Password!", "Error Sign In",ERROR_MESSAGE);
        //this.setVisible(true);
        
    }//GEN-LAST:event_signinBtnActionPerformed

    private void signupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupBtnActionPerformed
        // TODO add your handling code here:
        signupForm sgnupfrm = new signupForm();
        sgnupfrm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_signupBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SigninForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SigninForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SigninForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SigninForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SigninForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel bdgPic;
    private javax.swing.JPasswordField passFld;
    private javax.swing.JLabel passTxt;
    private javax.swing.JButton signinBtn;
    private javax.swing.JLabel signinTxt;
    private javax.swing.JButton signupBtn;
    private javax.swing.JTextField useridFld;
    private javax.swing.JLabel useridTxt;
    private javax.swing.JPanel whole;
    // End of variables declaration//GEN-END:variables
}
